;;;; asd-generator-data.asd

((#:package)
 (#:helper (:rest))
 (#:protocol)
 (#:constants)
 (#:lib (#:safe-reader (#:utils)
		       (:rest)))
 (#:data (:rest)) 
 (#:impl (:rest)
	 (#:shard (#:message)
		  (#:password)
		  (#:persona)
		  (:rest))
	 (#:server (:rest)))
 (#:gateway))
